In [3]:
import numpy as np

def sample_ecdf(qe,pe = None,x=None,data_range=[0,1]):
    # 
    #qe: empirical quantile 
    #pe: empirical cumulative probability
    #u: uniform random variable
    #data_range: range of data

    if x is None:
        x = np.random.uniform(0, 1)
    if x < data_range[0] or x > data_range[1]:
        raise ValueError('x must be in the range of data')

    if pe is None:
        pe = np.linspace(0, 1, len(qe))
    if len(qe) != len(pe):
        raise ValueError('length of qe and pe must be the same')

    qe_array = np.array(qe)
    pe_array = np.array(pe)

    result = (np.min(qe_array[pe_array>=x]) if x <= max(pe) else data_range[1]) 

    return result

In [7]:

sample_ecdf (qe = [1,2,3],x = 0.3,  data_range=[0, 4]) 

2

In [ ]:
        ecdf = ECDF(self.summary.scale)
        pe = ecdf.y
        qe = ecdf.x

        

In [11]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = 3

a[b>=a]



array([1, 2, 3])

In [39]:
import numpy as np
import numpy.linalg as npl
a = np.random.randn(3, 3) 


In [40]:
A = a@a.T
A

array([[ 6.15456105, -1.82502677, -2.40609733],
       [-1.82502677,  5.75025649,  2.94587508],
       [-2.40609733,  2.94587508,  3.19444689]])

In [41]:
u, s, vh = np.linalg.svd(A, full_matrices=True)

In [17]:
vh

array([[-0.31255196, -0.05226616, -0.94846166],
       [-0.29671174, -0.94315262,  0.1497507 ],
       [-0.902371  ,  0.32822459,  0.27927622]])

In [42]:
u0 = u[0].reshape(3,1)
u0


array([[-0.61460953],
       [-0.74916283],
       [ 0.24700238]])

In [43]:
npl.matrix_rank(u0@u0.T)

1

In [25]:
np.matmul( u[0], np.transpose(u[0]) )


1.0

In [29]:
u[0]

array([-0.31255196, -0.29671174, -0.902371  ])

In [8]:
np.pi

3.141592653589793

In [36]:
from math import cos, exp, pi, sqrt
from scipy.integrate import quad
import numpy as np

# function we want to integrate
def integrand(x,mu,mu1,mu0,sigma,pi0):
    return exp(-(x-mu)**2/2/sigma**2)/sqrt(2*pi*sigma**2) * (pi0*exp(-(x-mu1)**2/2/sigma**2) ) / (pi0*exp(-(x-mu1)**2/2/sigma**2) + (1-pi0)*exp(-(x-mu0)**2/2/sigma**2)) 


def expint( mu,mu1,mu0,sigma,pi0):
    return quad(integrand,  -5, 5, args=(mu,mu1,mu0,sigma,pi0))[0]



vec_expint = np.vectorize(expint)


In [37]:
[expint(0.75,0.75,0.25,0.2,0.2),expint(0.25,0.75,0.25,0.2,0.2) ]




[0.7158228053130965, 0.07104429867172588]

In [3]:
vec_expint(1,1,0,0.5,0.5)

/var/folders/gs/mk2wx9yn4mxgrjsmlxbw_b3w0000gn/T/ipykernel_90229/3238781087.py:7: RuntimeWarning: invalid value encountered in double_scalars
  return exp(-(x-mu)**2/2/sigma**2)/sqrt(2*pi*sigma**2) * (pi0*exp(-(x-mu1)**2/2/sigma**2) ) / (pi0*exp(-(x-mu1)**2/2/sigma**2) + (1-pi0)*exp(-(x-mu0)**2/2/sigma**2))
/var/folders/gs/mk2wx9yn4mxgrjsmlxbw_b3w0000gn/T/ipykernel_90229/3238781087.py:11: IntegrationWarning: The occurrence of roundoff error is detected, which prevents 
  the requested tolerance from being achieved.  The error may be 
  underestimated.
  return quad(integrand,  -np.inf, np.inf, args=(mu,mu1,mu0,sigma,pi0))[0]


ZeroDivisionError: float division by zero